name: CI/CD Pipeline

on:
  push:
    branches:
      - main   
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Game Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/game-service:latest ./game-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/game-service:latest

      - name: Build & Push Order Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest ./order-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

      - name: Build & Push Analytics Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/analytics-service:latest ./analytics-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/analytics-service:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
